Input:
 - path : ["/Users/chiu.i-huan/Desktop/new_scientific/GeAnalysis/data/JPARC_2021Apri/"]
 - file : ["Ti/203080_beam.root"]
 - file : ["Al/203081_beam.root"]
 - file : ["Fe/203082_beam.root"]
 - file : ["White/203084_beam.root"]
 - file : ["Black/203086_beam.root"]
# - file : ["NWA4734/203088_beam.root"]
 - file : ["DEW12007/203079_beam.root"]
 - file : ["DEW12007_bar/203089_beam.root"]
 - file : ["DEW12007_bar_35MeV/203095_beam.root"]
# - file : ["Blank_dsl9/203090_beam.root"]
# - file : ["Blank_dsl13/203091_beam.root"]
 - file : ["Blank_dsl20/203092_beam.root"]
# - file : ["Blank_35MeV/203094_beam.root"]

AtomTable:
 - O(3-2) : [24.8444, 0.162809]
 - O(4-2) : [33.5848, 0.213961]
 - O(5-2) : [37.5245, 0.268892]
 - O(2-1) : [133.445, 0.280050]
 - O(3-1) : [158.327, 0.336837]
 - O(4-1) : [167.076, 0.389773]
 - O(5-1) : [171.092, 0.498320]
 - Be(2-1) : [33.3729, 0.213961]
 - Be(4/5-1) : [42.8012, 0.306654]
 - Mg(5-3) : [28.9018, 0.236263]
 - Mg(3-2) : [56.2303, 0.339504]
 - Mg(5-2) : [83.8748, 0.310747]
 - Mg(7-2) : [92.7901, 0.329665]
 - Al(4-3) : [23.0743, 0.154448]
 - Al(5-3) : [33.7455, 0.190327]
 - Al(3-2) : [66.0625, 0.237007]
 - Al(4-2) : [89.1923, 0.300842]
 - Al(5-2) : [99.7744, 0.345302]
 - Si(4-3) : [26.7014, 0.191244]
 - Si(3-2) : [76.42, 0.300447]
 - Si(4-2) : [103.427, 0.602385]
 - Si(5-2) : [115.570, 0.453923]
 - Ca(4-3) : [54.65, 0.217937]
 - Ca(5-3) : [80.0657, 0.406603]
 - Ca(6-3) : [92.7901, 0.329665]
 - Ca(3-2) : [156.772, 0.417136]
 - Fe(5-4) : [42.78, 0.180674]
 - Fe(6-4) : [66.0339, 0.269578]
 - Fe(7-4) : [80.0756, 0.369917]
 - Fe(4-3) : [92.49, 0.302299]
 - Fe_gamma : [125.882, 0.261210]
 - Fe(5-3) : [135.593, 0.457524]
 - Fe(6-3) : [158.802, 0.531808]
 - Cu(5-4) : [53.3110, 0.269089]
 - Cu(6-4) : [82.2328, 0.474715]
 - Cu(4-3) : [115.61, 0.453923]
 - Cu(10-4) : [125.876, 0.343788]
 - Ti(5-4) : [30.6524, 0.182589]
 - Ti(6-4) : [47.1945, 0.243082]
 - Ti(4-3) : [66.2919, 0.227052]
 - Ti(5-3) : [96.9189, 0.301125]
 - Ti(6-3) : [113.562, 0.475476]
 - Ti(3-2) : [189.941, 0.369541]

